### ISSUE TITLE
Script tries to write under / directory if $INSTAGRAM not set

### ISSUE THREAD

**Issue by tvendelin** [kartikayuni/ffmpeg-script#1]
If `$INSTAGRAM` environment variable is not set by the user, the script will try to write to a file under `/` (root) directory, which is not what you want.

Ideas:
- Throw an error message advising to set `$INSTAGRAM` to pint to a directory intended for your script's output, if `$INSTAGRAM` is not set or, more precisely, is not a directory
- Use some default value if `$INSTAGRAM`  is not set or empty. For example, users `$HOME` or `$PWD`. Print a warning message.

**Comment by tvendelin** [comment]
You should explain, why is it closed :)

**Comment by kartikayuni** [comment]
Fixed. Thank you
